name="vid-best-mini"
main="src/index.js"
compatibility_date="2026-08-05"
[assets]
directory="public"
[[d1_databases]]
binding="DB"
database_name="video-reviews-db"
[[r2_buckets]]
binding="BUCKET"
bucket_name="vid-assets"
